#
#  Copyright 2022 Red Hat
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

FROM openjdk:17-alpine

LABEL maintainer="Harald Pehl <hpehl@redhat.com>"

ENV JBOSS_HOME /opt/jboss/wildfly
ARG WILDFLY_VERSION
COPY wildfly-${WILDFLY_VERSION}.tar.gz /

USER root
RUN mkdir -p ${JBOSS_HOME} \
    && tar xf /wildfly-${WILDFLY_VERSION}.tar.gz --directory=/ \
    && mv /wildfly-${WILDFLY_VERSION}/* ${JBOSS_HOME} \
    && rm /wildfly-${WILDFLY_VERSION}.tar.gz \
    && adduser --disabled-password --gecos "" jboss \
    && chown -R jboss:0 ${JBOSS_HOME} \
    && chmod -R g+rw ${JBOSS_HOME}

USER jboss
RUN ${JBOSS_HOME}/bin/add-user.sh -u admin -p admin --silent
RUN for conf in ${JBOSS_HOME}/standalone/configuration/standalone*.xml; do sed -e 's/<http-interface\(.*\)security-realm="ManagementRealm"\(.*\)>/<http-interface\1\2>/' -e 's/<http-interface\(.*\)http-authentication-factory="management-http-authentication"\(.*\)>/<http-interface\1\2>/' -e 's/<http-upgrade\(.*\)sasl-authentication-factory="management-sasl-authentication"\(.*\)\/>/<http-upgrade\1\2\/>/' "${conf}" > "${conf%%.*}-insecure.${conf#*.}"; done
RUN sed -i '/allowed-origins=".*"/! s/<http-interface\(.*\)>/<http-interface\1 allowed-origins="http:\/\/localhost:8888 http:\/\/localhost:9090 http:\/\/hal:9090 http:\/\/hal.github.io https:\/\/hal.github.io">/' ${JBOSS_HOME}/standalone/configuration/standalone*.xml

ENV LAUNCH_JBOSS_IN_BACKGROUND true
EXPOSE 8080 9990
ENTRYPOINT ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
CMD ["-c", "standalone.xml"]
