ARG WILDFLY_VERSION=latest
ARG DOCKER_BASE=jboss/wildfly
FROM ${DOCKER_BASE}:${WILDFLY_VERSION}

LABEL maintainer="Harald Pehl <hpehl@redhat.com>"

RUN /opt/jboss/wildfly/bin/add-user.sh -u admin -p admin --silent
RUN sed -e 's/<http-interface\(.*\)security-realm="ManagementRealm"\(.*\)>/<http-interface\1\2>/' -e 's/<http-interface\(.*\)http-authentication-factory="management-http-authentication"\(.*\)>/<http-interface\1\2>/' -e 's/<http-upgrade\(.*\)sasl-authentication-factory="management-sasl-authentication"\(.*\)\/>/<http-upgrade\1\2\/>/' /opt/jboss/wildfly/domain/configuration/host.xml > /opt/jboss/wildfly/domain/configuration/host-insecure.xml
RUN sed -i '/allowed-origins=".*"/! s/<http-interface\(.*\)>/<http-interface\1 allowed-origins="http:\/\/localhost:8888 http:\/\/localhost:9090 http:\/\/hal:9090 http:\/\/hal.github.io https:\/\/hal.github.io">/' /opt/jboss/wildfly/domain/configuration/host*.xml
RUN sed -i '/<server .*auto-start.*/! s/\(<server .*"\)\(>\)$/\1 auto-start="false"\2/' /opt/jboss/wildfly/domain/configuration/host*.xml
RUN sed -i '/<server .*auto-start.*/! s/\(<server .*"\)\(\/>\)$/\1 auto-start="false"\2/' /opt/jboss/wildfly/domain/configuration/host*.xml
RUN sed -i 's/\(<server.*auto-start="\)true\(".*\)/\1false\2/' /opt/jboss/wildfly/domain/configuration/host*.xml

EXPOSE 8080 9990
ENTRYPOINT ["/opt/jboss/wildfly/bin/domain.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
CMD ["-c", "domain.xml"]
