name: Verify Codebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    name: Verify Codebase
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v5
      - name: Initialize CodeQL
        id: init-codeql
        uses: github/codeql-action/init@v4
        with:
          languages: java
      - name: Set up JDK
        id: setup-jdk
        uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Verify
        id: verify
        run: $MVN -P skip-gwt verify
      - name: Perform CodeQL Analysis
        id: perform-codeql
        uses: github/codeql-action/analyze@v4
